# Generated by Django 5.1.7 on 2025-03-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix_Analysis', '0002_alter_movie_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
