# Generated by Django 5.1.7 on 2025-04-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix_Analysis', '0003_alter_movie_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='listed_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
